### ISSUE TITLE
qbittorrent optional authentication the same as buildarr-sonarr

### ISSUE THREAD

**Issue by scratchmex** [buildarr/buildarr-radarr#48]
in sonar you can omit the authentication if you have it disabled. the spec is the following
```
username: Optional[str] = None
password: Optional[SecretStr] = None
```

will be nice to match the spec of both

**Comment by Callum027** [comment]
Hi @scratchmex, thanks for the bug report.

In this case the Radarr plugin is actually incorrect, and it should be defined as you've explained in your comment.

In the next minor release I will include a patch that addresses this.

**Comment by Callum027** [comment]
Thanks for waiting. The fix for this issue has been released as:

* Docker Container: [`callum027/buildarr:0.7.6`](https://hub.docker.com/r/callum027/buildarr) (or update your local container if using `latest`)
* Windows Installer: [`buildarr-installer-0.7.6-x64.exe`](https://github.com/buildarr/buildarr-installer/releases/tag/v0.7.6)
* Python Package: [`buildarr-radarr==0.2.5`](https://pypi.org/project/buildarr-radarr/0.2.5)

Please give the new version a try to check that it resolves your issue.

**Comment by Callum027** [comment]
As this has been fixed in the current release for some time and I have received no feedback, I will close this issue as completed.

Please let me know if you have any more problems with this issue, or Buildarr in general.
